eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    appname: user
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 4

server:
  port: 8070

spring:
  cloud:
    config:
      enabled: false
  application:
    name: user
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/user?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Azertyuiop23
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

jwt:
  secret: ew0KICAic3ViIjogIjEyMzQ1Njc4OTAiLA0KICAibmFtZSI6ICJKb2huIERvZSIsDQogICJhZG1pbiI6IHRydWUsDQogICJpYXQiOiAxNzQxMTczOTM5DQp9
  expiration: 3600000 # Example: 1 hour in milliseconds

application:
  config:
    users-url: http://localhost:8070/api/auth/register