eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: offres
          uri: http://localhost:8090
          predicates:
            - Path=/api/offres
        - id: user
          uri: http://localhost:8070
          predicates:
            - Path=/api/auth/register
          filters:
            - StripPrefix=2
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG